-- Reset complet MaterniteCare (version finale)
DROP VIEW IF EXISTS vue_patiente_public CASCADE;
DROP VIEW IF EXISTS vue_soignant_restreint CASCADE;
DROP TABLE IF EXISTS log_acces CASCADE;
DROP TABLE IF EXISTS permission CASCADE;
DROP TABLE IF EXISTS nouveau_ne CASCADE;
DROP TABLE IF EXISTS accouchement CASCADE;
DROP TABLE IF EXISTS ordonnance CASCADE;
DROP TABLE IF EXISTS vaccination CASCADE;
DROP TABLE IF EXISTS document_medical CASCADE;
DROP TABLE IF EXISTS rendez_vous CASCADE;
DROP TABLE IF EXISTS constante_vitale CASCADE;
DROP TABLE IF EXISTS admission CASCADE;
DROP TABLE IF EXISTS grossesse CASCADE;
DROP TABLE IF EXISTS patiente CASCADE;
DROP TABLE IF EXISTS lit CASCADE;
DROP TABLE IF EXISTS personnel_soignant CASCADE;
DROP TABLE IF EXISTS workspace CASCADE;

DROP TYPE IF EXISTS type_workspace CASCADE;
DROP TYPE IF EXISTS role_personnel CASCADE;
DROP TYPE IF EXISTS groupe_sanguin CASCADE;
DROP TYPE IF EXISTS type_grossesse CASCADE;
DROP TYPE IF EXISTS niveau_risque CASCADE;
DROP TYPE IF EXISTS statut_grossesse CASCADE;
DROP TYPE IF EXISTS statut_admission CASCADE;
DROP TYPE IF EXISTS type_lit CASCADE;
DROP TYPE IF EXISTS type_rdv CASCADE;
DROP TYPE IF EXISTS statut_rdv CASCADE;
DROP TYPE IF EXISTS type_document CASCADE;
DROP TYPE IF EXISTS type_accouchement CASCADE;
DROP TYPE IF EXISTS sexe_type CASCADE;
DROP TYPE IF EXISTS etat_sante_nne CASCADE;

DROP EXTENSION IF EXISTS "pgcrypto";